# Adapted from https://github.com/ChrisPenner/haskell-stack-travis-ci
language: nix
sudo: true

cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal
        - $HOME/.stack
        - .stack-work

matrix:
  fast_finish: true
  include:
    # Add build targets here
    - env: GHCVER=8.2.1 CACHE_NAME=8.2.1 BUILD_BINARY=1
      compiler: ": #stack 8.2.1"
      addons: {apt: {packages: [ghc-8.2.1], sources: [hvr-ghc]}}

    - env: GHCVER=8.2.1 CACHE_NAME=8.2.1-osx BUILD_BINARY=1
           LDFLAGS=-L/usr/local/opt/readline/lib CFLAGS=-I/usr/local/opt/readline/include
      os: osx
      compiler: ": #stack 8.2.1"
      addons: {apt: {packages: [ghc-8.2.1], sources: [hvr-ghc]}}

install:
 - unset CC
 - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
 - ./.travis/install-ghr.sh
 - ./.travis/install-stack.sh
 - ./.travis/install-dapptools.sh

script:
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - GHC_OPTIONS="-Werror"
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
   stack install readline --extra-include-dirs=/usr/local/opt/readline/include
                          --extra-lib-dirs=/usr/local/opt/readline/lib;
   else
   wget "http://mirrors.kernel.org/ubuntu/pool/universe/libs/libsecp256k1/libsecp256k1-0_0.1~20170810-1_amd64.deb" ;
   wget "http://mirrors.kernel.org/ubuntu/pool/universe/libs/libsecp256k1/libsecp256k1-dev_0.1~20170810-1_amd64.deb" ;
   sudo dpkg -i libsecp256k1-0_0.1~20170810-1_amd64.deb libsecp256k1-dev_0.1~20170810-1_amd64.deb ;
   fi
 - |
   set -ex
   # Run tests
   ls -R "$HOME/.nix-profile/"
   stack --no-terminal test --ghc-options="$GHC_OPTIONS" --extra-lib-dirs="$HOME/.nix-profile/lib/" --extra-include-dirs="$HOME/.nix-profile/include/"
   set +ex

after_success:
 - |
   # Build and ship binary
   export BUILD_BINARY=true
   export TRAVIS_TAG=$(git rev-parse HEAD)
   ./.travis/attach-binary.sh

notifications:
  email: false
