# Adapted from https://github.com/ChrisPenner/haskell-stack-travis-ci
language: python
python:
  - 3.6

sudo: true

cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal
        - $HOME/.stack
        - .stack-work
        - /usr/local/include
        - /usr/local/lib
    timeout: 1000

matrix:
  fast_finish: true
  include:
    # Add build targets here
    - env: CACHE_NAME=linux BUILD_BINARY=1
    - env: CACHE_NAME=osx   BUILD_BINARY=1
           STACK_OPTS="--no-run-tests --extra-include-dirs=/usr/local/opt/readline/include --extra-lib-dirs=/usr/local/opt/readline/lib"
           LDFLAGS=-L/usr/local/opt/readline/lib CFLAGS=-I/usr/local/opt/readline/include
      os: osx
      language: minimal

install:
 - unset CC
 - export PATH=$HOME/.local/bin:$PATH
 - ./.travis/install-libsecp256k1.sh
 - ./.travis/install-libff.sh
 - ./.travis/install-ghr.sh
 - ./.travis/install-stack.sh
 - ./.travis/install-solc.sh
 - ./.travis/install-crytic-compile.sh

script:
 - PATH=$HOME/.local/bin:$PATH
 - echo "$(stack ghc -- --version) [$(stack ghc -- --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - GHC_OPTIONS="-Werror"
 - STACK_OPTS="$STACK_OPTS --extra-include-dirs=/usr/local/include --extra-lib-dirs=/usr/local/lib"
 - |
   set -ex
   export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
   
   run_tests_using () {
     cp ~/.local/bin/$1 ~/.local/bin/solc || true
     stack --no-terminal test --ghc-options="$GHC_OPTIONS" $STACK_OPTS
   }

   #run_tests_using "solc-0.4.25"
   run_tests_using "solc-0.5.7"
   run_tests_using "solc-0.6.2"
   set +ex

notifications:
  email: false
